# Generated by Django 3.1.5 on 2021-01-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='doc_num',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
